name: CI to Docker hub 

on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run shell
        run: |- 
          ls -la;
          pwd
          bash build.xiaomi_miwifi-mini.sh
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          name: nightly-build-${{ steps.date.outputs.date }}
          files: bin/targets/ramips/mt7620/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
