name: public package

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * SAT'
jobs:
  docker:
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/imagebuilder:ramips-mt7620-openwrt-21.02
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run shell
        run: |- 
          ls -la;
          pwd

      - name: Run shell
        run: |- 
          WORKDIR=`pwd`
          cd /home/build/openwrt/
          ls -la;
          pwd
          make -j12 image \
          PROFILE="xiaomi_miwifi-mini" \
          PACKAGES="comgt kmod-usb-serial kmod-usb-serial-option kmod-usb-serial-wwan usb-modeswitch luci-app-mwan3 block-mount kmod-fs-ext4 kmod-fs-exfat kmod-fs-autofs4 kmod-usb-storage kmod-usb-storage-uas usbutils f2fs-tools kmod-fs-f2fs kmod-usb-ohci kmod-usb-uhci e2fsprogs fdisk kmod-usb-net-rndis kmod-nls-base kmod-usb-core kmod-usb-net kmod-usb-net-cdc-ether kmod-usb2 luci kmod-dummy relayd luci-compat $WORKDIR/ext-package/luci-theme-argon_2.2.5-20200914_all.ipk "
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: images-info
          path: |
            /home/build/openwrt/bin/targets/ramips/mt7620/
            
